version: '3'
services:
  db:
    image: postgres
    volumes:
      - pai-gres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  web:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/pai-auth
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

  vue:
    build: ./front
    volumes:
      - ./front:/pai-auth
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    command: npm run serve

volumes:
  pai-gres:
  bundle:
